services:
  llama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - '11434:11434'
    volumes:
      - ./ollama:/root/.ollama
    extra_hosts:
     - host.docker.internal:host-gateway
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    restart: always